### ISSUE TITLE
Not supported on Erlang 26 due to outdated mix_erlang_tasks module

### ISSUE THREAD

**Issue by chrism2671** [zyield/block_keys#35]
Recommend switching reps to 

https://hex.pm/packages/libsecp256k1_nash_fork

**Comment by tzumby** [comment]
Thanks @chrism2671, I'll look into switching to that. 

Long term I think something like the Rust Nif would be much better though https://hex.pm/packages/ex_secp256k1

**Comment by tzumby** [comment]
Hey @chrism2671, I have an open PR that addresses this. Finally got around to bringing the Rust based secp256k1 library.
